Hack1_Django_Based_CV/accounts/urls.py
from django.urls import path
from accounts.views import  SignUpView
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import ProfileView, AccountLoginView

app_name = 'accounts'

urlpatterns = [
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='greetings'), name='logout'),
    path('profile/<int:pk>', ProfileView.as_view(template_name='profile.html'), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
  
]

Hack1_Django_Based_CV/cv_builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('digital_resume.urls')),
    # path('digital_resume/', include('digital_resume.urls')),
    path("accounts/", include('accounts.urls')),
    path('pdf/', include('pdf_builder.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Hack1_Django_Based_CV/digital_resume/urls.py
from django.urls import path
from . import views

app_name = 'digital_resume'

urlpatterns = [
    path('', views.GreetingsView.as_view(), name='greetings'),
    path('personal-info/create', views.PersonalInfoCreateView.as_view(), name='personal-info-create'),
    path('summary/create/', views.SummaryCreateView.as_view(), name='summary-create'),
    path('technical-skill/create/', views.TechnicalSkillCreateView.as_view(), name='technical-skill-create'),
    path('technical-project/create/', views.TechnicalProjectCreateView.as_view(), name='technical-project-create'),
    path('experience/create/', views.ExperienceCreateView.as_view(), name='experience-create'),
    path('education/create/', views.EducationCreateView.as_view(), name='education-create'),
    path('language/create/', views.LanguageCreateView.as_view(), name='language-create'),
]

Hack1_Django_Based_CV/pdf_builder/urls.py
from django.urls import path
from .views import generate_pdf, preview_information

app_name = 'pdf_builder'

urlpatterns = [
    path('generate-pdf/', generate_pdf, name='generate-pdf'),
    path('preview/', preview_information, name='preview')
]

Hack1_Django_Based_CV/digital_resume/models.py
from django.db import models
from accounts.models import UserProfile


class PersonalInfo(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='personal_info')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    job_title = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    github_url = models.URLField()
    linkedin_url = models.URLField()
    portfolio_url = models.URLField()
    # other fields as per your requirements

class Summary(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    summary_text = models.TextField()

class TechnicalSkill(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='tech_skills')
    skill_name = models.CharField(max_length=255)

    def __str__(self):
        return self.skill_name

class TechnicalProject(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='tech_projects')
    project_name = models.CharField(max_length=255)
    github_url = models.URLField()
    demo_url = models.URLField()
    project_description = models.TextField()

    def __str__(self):
        return self.project_name

class Experience(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='experience')
    job_title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    experience_description = models.TextField()

    def __str__(self):
        return self.job_title

class Education(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='education')
    program_name = models.CharField(max_length=255)
    institution_name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.program_name

class Language(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='languages')
    language_name = models.CharField(max_length=255)
    proficiency_level = models.CharField(max_length=255)

    def __str__(self):
        return self.language_name

Hack1_Django_Based_CV/digital_resume/forms.py
from django import forms
from django.forms import formset_factory, HiddenInput
from .models import TechnicalProject, TechnicalSkill, Experience, Education, Language, Summary


class SummaryForm(forms.ModelForm):
    class Meta:
        model = Summary
        fields = ['user_profile', 'summary_text']
        widgets = {
            'user_profile': HiddenInput(),
        }


class TechnicalSkillForm(forms.ModelForm):
    class Meta:
        model = TechnicalSkill
        fields = ['user_profile', 'skill_name']
        widgets = {
            'user_profile': HiddenInput(),
        }


class TechnicalProjectForm(forms.ModelForm):
    class Meta:
        model = TechnicalProject
        fields = ['user_profile', 'project_name', 'github_url', 'demo_url', 'project_description']
        widgets = {
            'user_profile': HiddenInput(),
        }


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['user_profile', 'job_title', 'company_name', 'start_date', 'end_date', 'experience_description']
        widgets = {
            'user_profile': HiddenInput(),
        }


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['user_profile', 'program_name', 'institution_name', 'start_date', 'end_date']
        widgets = {
            'user_profile': HiddenInput(),
        }


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ['user_profile', 'language_name', 'proficiency_level']
        widgets = {
            'user_profile': HiddenInput(),
        }

Hack1_Django_Based_CV/digital_resume/views.py
from typing import Any, Dict
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.forms import formset_factory
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.urls import reverse_lazy
from .models import *
from django.views.generic import TemplateView
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import UserProfile

# Create your views here.
class BaseCreateView(FormView):
    formset_class = None  # Override this in child views
    template_name = None  # Override this in child views
    success_url = None  # Override this in child views

    def get_form(self, form_class=None):
        formset = self.formset_class(**self.get_form_kwargs())
        for form in formset:
            form.fields['user_profile'].initial = self.request.user.profile
        return formset

    def form_valid(self, form):
        for form_instance in form:
            if form_instance.is_valid():
                form_instance.save()
        return super().form_valid(form)

class GreetingsView(TemplateView):
    def get(self, request):
        return render(request, 'digital_resume/greetings.html')

class PersonalInfoCreateView(LoginRequiredMixin, CreateView):
    model = PersonalInfo
    fields = ['first_name', 'last_name', 'job_title', 'city', 'phone_number', 'email', 'github_url', 'linkedin_url', 'portfolio_url']
    template_name = 'digital_resume/personal_info_form.html'
    success_url = reverse_lazy('digital_resume:summary-create')

    def form_valid(self, form):

        user_profile = UserProfile.objects.get(user=self.request.user)

        form.instance.user_profile = user_profile
        return super().form_valid(form)

class SummaryCreateView(FormView):
    form_class = SummaryForm
    template_name = 'digital_resume/summary_form.html'
    success_url = reverse_lazy('digital_resume:technical-skill-create')
    

    def get_form(self, form_class=None) -> Dict[str, Any]:
        form = super().get_form(form_class)
        user_profile = self.request.user.profile
        form.fields['user_profile'].initial = user_profile
        return form
    
    def form_valid(self, form) -> HttpResponse:
        form.save()
        return super().form_valid(form)


class TechnicalSkillCreateView(BaseCreateView):
    formset_class = formset_factory(TechnicalSkillForm, extra=2)
    template_name = 'digital_resume/technical_skill_form.html'
    success_url = reverse_lazy('digital_resume:technical-project-create')
    

class TechnicalProjectCreateView(BaseCreateView):
    formset_class = formset_factory(TechnicalProjectForm, extra=2)
    template_name = 'digital_resume/technical_project_form.html'
    success_url = reverse_lazy('digital_resume:experience-create')


class ExperienceCreateView(BaseCreateView):
    formset_class = formset_factory(ExperienceForm, extra=2)
    template_name = 'digital_resume/experience_form.html'
    success_url = reverse_lazy('digital_resume:education-create')


class EducationCreateView(BaseCreateView):
    formset_class = formset_factory(EducationForm, extra=2)
    template_name = 'digital_resume/education_form.html'
    success_url = reverse_lazy('digital_resume:language-create')


class LanguageCreateView(BaseCreateView):
    formset_class = formset_factory(LanguageForm, extra=3)
    template_name = 'digital_resume/language_form.html'
    success_url = reverse_lazy('pdf_builder:preview')

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>CV Builder</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=Marvel&display=swap" rel="stylesheet">
           
    </head>
    <body>
        <main class="container">
                
            <div class="header">
                {% include 'digital_resume/nav.html' %}
            <!-- Add your header content here -->
            </div>
                    
            <div class="context">
                {% block content %}
                {% endblock %}
            </div>
        </main>
    </body>
</html>

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/education_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Education</h2>
    <div>
        <form method="post" action="{% url 'digital_resume:education-create' %}">
            {% csrf_token %}
            {{ form.management_form }}
            {%for form_instance in form%}
            <div>
                {{ form_instance|crispy}}
                <!-- {{ form.non_form_errors }} -->
            </div>
            {%endfor%}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/experience_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Experience</h2>
        <div> 
             <form method="post" action="{% url 'digital_resume:experience-create' %}">
                {% csrf_token %}
                {{ form.management_form }}
                {%for form_instance in form%}
        <div>
            {{ form_instance|crispy}}
            <!-- {{ form.non_form_errors }} -->
        </div>
        {%endfor%}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/greetings.html
{% extends 'digital_resume/base.html' %}

{% block content %}
<div class="greetings-container">
  <div class="greetings1">
    <h1>WELCOME TO THE DIGITAL CV BUILDER</h1>
  </div>
  
  <div class="greetings2">
    <h2>Fill the forms and get a pdf file with your CV ready to send</h2>
  </div>
</div>


{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/language_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Languages</h2>
        <div> 
            <form method="post" action="{% url 'digital_resume:language-create' %}">
                {% csrf_token %}
                {{ form.management_form }}
                {%for form_instance in form%}
                <div>
                    {{ form_instance|crispy}}
                    <!-- {{ form.non_form_errors }} -->
                </div>
                {%endfor%}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/nav.html
<div class="navbar">
    
            <div class="name">
                <h1>CV Builder</h1>
            </div>
            <div class="login">
                {{user}}
                {% if user.is_authenticated %}
                {% if user.profile %}
                <br>
                <li class="login-wrapper"><a href="{% url 'accounts:profile' user.profile.id %}">Profile</a></li>
            
                <li class="login-wrapper"><a href="{% url 'accounts:logout' %}?next=/">Logout</a></li>
            </div>

            <div >
                    <ul class="links">
                     <li class="link-wrapper"><a href="{% url 'digital_resume:personal-info-create' %}">Personal Info</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:summary-create' %}">Summary</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:technical-skill-create' %}">Technical Skills</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:technical-project-create' %}">Technical Project</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:experience-create' %}">Experience</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:education-create' %}">Education</a></li>
                      <li class="link-wrapper"><a href="{% url 'digital_resume:language-create' %}">Languages</a></li>
                      <li class="link-wrapper"><a href="{% url 'pdf_builder:preview' %}">Preview CV</a></li>
                      <li class="link-wrapper"><a href="{% url 'pdf_builder:generate-pdf' %}">Create PDF</a></li>
                      <!-- Add more navigation items for other forms -->
                
                </ul>
            </div>
        {% endif %}
        {% else %}
        
        <div class="login">
                    <li class="login-wrapper"><a href="{% url 'accounts:signup' %}">Sign Up</a></li> <br>
                    <li class="login-wrapper"><a href="{% url 'accounts:login' %}">Login</a></li>
        </div>

          
        {% endif %}
    
    
</div>

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/personal_info_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Personal Information</h2>
    <form method="post" action="{% url 'digital_resume:personal-info-create' %}">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/summary_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Summary</h2>
    <form method="post" action="{% url 'digital_resume:summary-create' %}">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/technical_project_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Technical Projects</h2>
    <div>
        <form method="post" action="{% url 'digital_resume:technical-project-create' %}">
            {% csrf_token %}
            {{ form.management_form }}
            {%for form_instance in form%}
            <div>
                {{ form_instance|crispy}}
                <!-- {{ form.non_form_errors }} -->
            </div>
        
            {%endfor%}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Hack1_Django_Based_CV/digital_resume/templates/digital_resume/technical_skill_form.html
{% extends 'digital_resume/base.html' %}
{%load crispy_forms_tags %} 
{% block content %}
    <h2>Technical Skills</h2>

    <form method="post" action="{% url 'digital_resume:technical-skill-create' %}">
        {% csrf_token %}
        {{ form.management_form }}
        {%for form_instance in form%}
        <div>
            {{ form_instance|crispy}}
            <!-- {{ form.non_form_errors }} -->
        </div>
            
    {%endfor%}
            <button type="submit">Save</button>
    </form>
{% endblock %}